version: '3.8'

services:
  nubit1:
    image: nubit:latest
    container_name: nubit-container1
    tty: true
    stdin_open: true
    command: ["bash", "-c", "curl -sL1 https://nubit.sh | bash"]
    deploy:
      restart_policy:
        condition: any
    build:
      context: .
    volumes:
      - /data_docker:/data_docker
