version: '3.8'

services:
  nubit1:
    image: validatorhub/nubit:latest
    container_name: nubit-container1

    tty: true
    stdin_open: true
    command: ["bash", "-c", "curl -sL1 https://nubit.sh | bash"]
    volumes:
      - nubit-data:/nubit-data
      - nubit-config:/nubit-node/config
    ports:
      - "2121:2121"
    deploy:
      restart_policy:
        condition: any

volumes:
  nubit-data:
    driver: local
  nubit-config:
    driver: local
